#!/bin/bash

DB=~/phone.txt

INSENSITIVITY=
ADD=no

while getopts ai option
do
    case $option in
        a)  ADD=yes
            ;;
        i)  INSENSITIVITY=-i
            ;;
        *)  echo "Illegal option $OPTARG" >&2
            exit 1
    esac
done

if [ $# -ne $OPTIND ]
then
    echo 'Takes exactly one argument' >&2
    exit 1
fi

if [ "$ADD" = yes ]
then
    if [ -n "$INSENSITIVITY" ]
    then
        echo 'Cannot specify both -a and -i' >&2
        exit 1
    fi
    printf '%s\n' "${!OPTIND}" >> "$DB"
else
    touch -a "$DB"
    grep $INSENSITIVITY -- "${!OPTIND}" "$DB" | sort -u
fi
